QUALITIES = 'qualities'
TRAITS = 'traits'
SKILLS = 'skills'
TALENTS = 'talents'
DICE = 'dice'
TEARING_DICE = 'tearing_dice'
PENETRATION = 'penetration'
FLAT_DAMAGE = 'flat_damage'
NAME = 'name'
ARMOR = 'armor'
WEAPON_CLASS = 'class'
RANGE = 'range'
DAMAGE_TYPE = 'damage_type'
CHARACTERISTICS = 'characteristics'
SKILLS = 'skills'
SPECIES = 'species'
SINGLE_SHOT = 'single_shot'
SEMI_AUTO = 'semi_auto'
FULL_AUTO = 'full_auto'
RANGE = 'range'
PACKAGE = '_package'
VEHICLE = 'vehicle'
PSYCHIC = 'psychic'
ENTITY = 'entity'
WOUNDS = 'wounds'


DUMMY = 'dummy'
