import os
ROOT_DIR = os.path.dirname(os.path.abspath(__file__))

WEAPON = 'weapon'
WEAPONS = 'weapons'
ATTACKER = 'attacker'
TARGET = 'target'
FIREMODE = 'firemode'
CLASS = 'class'
MELEE = 'melee'
RANGED_CLASSES = ['pistol', 'basic', 'heavy', 'mounted']
NUM_ATTACKS = 'num_attacks'
ATTACKER_MAG = 'attacker_mag'
TARGET_MAG = 'target_mag'
ROLL_TARGET = 'roll_target'
ROLL_RESULT = 'roll_result'
FORCE_FIELD = 'force_field'
OVERLOAD_MAX = 'overload_max'
PROTECTION_MAX = 'protection_max'
SIZE = 'size'
RANGE = 'range'
AD_HOC = 'ad_hoc'
DEGREES_OF_SUCCESS = 'degrees_of_success'
NUM_HITS = 'num_hits'
ROLLED_DAMAGE = 'rolled_damage'
RAW_DAMAGE = 'raw_damage'
OFFENSIVE_MODIFIERS = 'offensive_modifiers'
DEFENSIVE_MODIFIERS = 'defensive_modifiers'
MODIFIER_EFFECTS = 'modifier_effects'
EFFECTIVE_DAMAGE = 'effective_damage'
MAGNITUDE_DAMAGE = 'magnitude_damage'
HIT_LOCATIONS = 'hit_locations'
ROLL_MODIFIERS = 'roll_modifiers'
DEBUG = 'debug'
RAW_WEAPON_STATS = 'raw_weapon_stats'
EFFECTIVE_ARMOR = 'effective_armor'
EFFECTIVE_TOUGHNESS = 'effective_toughness'
EFFECTIVE_PSY_RATING = 'effective_psy_rating'
BLOCKED = 'blocked'
RATE_OF_FIRE = 'rate_of_fire'

# States
AIMED = 'aimed'
OVERLOADED = 'overloaded'
CHARGED = 'charged'
COVER = 'cover'
JAMMED = 'jammed'

# Commands
RUN = 'run'
SUGGEST = 'suggest'
QUIT = 'quit'
CLEAR = 'clear'
AUTO = 'auto'
DAMAGE = 'damage'
SAVE = 'save'
LOAD = 'load'
